# Generated by Django 4.0.4 on 2022-05-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoChatterbotStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('conversation', models.CharField(max_length=32)),
                ('in_response_to', models.CharField(blank=True, max_length=255, null=True)),
                ('persona', models.CharField(max_length=50)),
                ('search_text', models.CharField(max_length=255)),
                ('search_in_response_to', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'django_chatterbot_statement',
                'managed': False,
            },
        ),
    ]
